### PR TITLE
Updated logrus to 1.0 to solve case insensitive import problem

### PR DESCRIPTION
**Pull request by vgarvardt**

### CODE REVIEW

**Comment by arekkas** [comment]
Thank you for the PR, where is this causing problems?

**Comment by vgarvardt** [comment]
After upgrading dependencies in the project I'm currently working on I go the following problem:

```
cmd/auth/server.go:17:2: case-insensitive import collision: "github.com/hellofresh/auth-service/vendor/github.com/Sirupsen/logrus" and "github.com/hellofresh/auth-service/vendor/github.com/sirupsen/logrus"
```

The problem is that `logrus` switched to lower-case package name in `1.0.0` and it causes problems with other dependencies that already updated and use lower-case package name.

**Comment by arekkas** [comment]
Unfortunately, the renaming of logrus is a huge f* mess, what library do you depend on - ory/common directly or e.g. fosite/hydra/ladon?

**Comment by vgarvardt** [comment]
Yes, this is true, but either you bump `logrus` to `1.0.0` and fix all dependant libraries (that I did for my project, and your library is the only 3rd party that I use), or you can not use other libraries that already bumped their dependency.

I use some functionality from `ory/common` and `ory/osin-storage` that depends on common.

**Comment by arekkas** [comment]
> fix all dependant libraries

Unfortunately, common is used in a lot of projects of ours, and I had to revert back to uppercase because there is just too many libraries out there still using uppercase logrus. Instead, I'd accept a PR that removes the common dependency in osin, but changing this in this library here will cause a bunch of issues for our other projects which is why I can't accept this, unfortunately.

**Pull request closed without merging**
